@baseUrl = http://localhost:3000

#RECADOS
GET {{baseUrl}}/recados
###
GET {{baseUrl}}/recados/365/
###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "recado":"Este é o recado que estou enviando.",
  "nova chave": "outro valor"
}

###
PATCH  {{baseUrl}}/recados/1
Content-Type: application/json

{
  "recado":"Este é o recado que estou enviando.",
  "atualizar": true
}

### AppControllerGetHello 

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota 

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico/