#PESSOAS
@baseUrl = http://localhost:3000
###

# LISTA TODAS AS PESSOAS 
###
GET {{baseUrl}}/pessoas/

# LISTA APENAS UMA PESSOA
###
GET {{baseUrl}}/pessoas/1

#CRIA UMA PESSOA
###
POST {{baseUrl}}/pessoas/10
Content-Type: application/json

  {
    "password": "250250250",
    "nome": "Jonh Doe"
  }

#REMOVE UMA PESSOA
###
DELETE {{baseUrl}}/pessoas/2

#ATUALIZA UMA PESSOA
###
PATCH {{baseUrl}}/pessoas/2
Content-Type: application/json

{
  "nome": "Jonh Doe"
}